### ISSUE TITLE
Cryptic characters in CLI

### ISSUE THREAD

**Issue by skaman82** [iNavFlight/inav-configurator#10] opened 2016-05-25 15:52 UTC
Sometimes when I enter the CLI Tab I see some cryptic characters.
![bildschirmfoto 2016-05-25 um 17 51 10](https://cloud.githubusercontent.com/assets/11768024/15546748/64d5e1ba-22a1-11e6-9850-d49c91b78d65.png)

**Comment by sppnk** [comment] 2016-05-25 17:27
Me too. I usually enter through bluetooth and EZGUI, so I dont know if the problem is in EZGUI itself. With cleanflight I dont connect much.

When I have the issue, the '#' character doenst appear, and I have to reset the FC to get it again.

**Comment by Ralf-W** [comment] 2016-07-31 11:17
Me too. But I use iNAV configurator on my laptop connected via bluetooth. So it is not coming from EZGUI itself. Sometimes I get not only cryptic characters, but some readable information too:

$M>htARM;ANGLE;HORIZON;AIR MODE;HEADING LOCK;MAG;HEADFREE;HEADADJ;NAV ALTHOLD;SURFACE;BEEPER;OSD SW;BLACKBOX;d$M&gtni
Entering CLI Mode, type 'exit' to return, or 'help'

**Comment by DzikuVx** [comment] 2017-01-21 21:45
Issue localized. It happens when there are pending MSP messages somewhere in the serial link when CLI is entered. #116 should fix this problem. Closing as implementation in place

**Closed by DzikuVx** 2017-01-21 21:45 UTC
