### ISSUE TITLE
RUSH_BLADE_F7 BMP280 Barometer doesn't work (need Fix)

### ISSUE THREAD

**Issue by NoviKurniawan** [iNavFlight/inav-configurator#1798] opened 2023-06-30 04:08 UTC
![Screenshot_15](https://github.com/iNavFlight/inav-configurator/assets/38303274/f7d6d484-fa7b-49c6-afb7-555b3b216aaa)
NEED FIX
Current Behavior
RUSHFPV RUSH BLADE F722 FLIGHT CONTROLLER FOR DJI DIGITAL FPV SYSTEM supports BMP280 (and it works fine in Betaflight and Emuflight), but not in iNav.
I tried the latest update (INAV 6.1.1) but still got the same error
thank you.

**Comment by MrD-RC** [comment] 2023-06-30 07:37
Duplicate of https://github.com/iNavFlight/inav/issues/9150

**Closed** 2023-06-30 07:37 UTC
