### ISSUE TITLE
iNav 2.0 tricopter mixer load issue

### ISSUE THREAD

**Issue by Roofneck** [iNavFlight/inav-configurator#493] opened 2018-06-27 11:39 UTC
Hi there,
I can't save tricopter mixer. All other mixes i can save but when i choose tricopter looks like save and reboot button does nothing.
iNav2.0 on Omnibus F3 Pro

**Comment by DzikuVx** [comment] 2018-06-27 12:47
Duplicate of #489

**Closed by DzikuVx** 2018-06-27 12:47 UTC
