### ISSUE TITLE
Toggling arming switch while connected to USB

### ISSUE THREAD

**Issue by Copterplt** [iNavFlight/inav-configurator#1753] opened 2023-04-07 14:11 UTC
I recently flashed I nav 6.0 on my dolphin with H743 WING V3.  I noticed when testing that if I arm the plane ( with or without battery power and connected to USB) and disarm, all outputs to the plane stop functioning.  I have to remove all power and reconnect to configuration to reestablish output movement.  If I toggle arming again, it repeats.  Not sure if this symptom is intentional.  I can send a diff file if you like.  I reported this previously in discord and was not sure I explained it thoroughly.

**Comment by DzikuVx** [comment] 2023-04-07 14:24
Duplicate of https://github.com/iNavFlight/inav/issues/8905
INAV 6.1 will fix it. Closing

**Closed by DzikuVx** 2023-04-07 14:24 UTC
