### ISSUE TITLE
V1.8 Preset Tab - not able to apply Preset to board

### ISSUE THREAD

**Issue by Pairan** [iNavFlight/inav-configurator#296] opened 2017-10-20 14:15 UTC
After having picked one preset the warning window shows up. But nothing happens if I click "save and reboot"

Running - OS: MacOS, Chrome: 61.0.3163.100, Configurator: 1.8.0

**Comment by fiam** [comment] 2017-10-20 15:30
@Pairan This seems like a duplicate of #284, which has been fixed in the repository (but not released yet). Would you mind testing the configurator from the master branch to see if the problem still exists?

**Comment by Pairan** [comment] 2017-10-20 15:31
sure … how to get it?1

**Comment by fiam** [comment] 2017-10-20 15:53
@Pairan You need to clone the repo and follow the instructions in the README. It can be a bit complicated.

**Comment by Pairan** [comment] 2017-10-20 15:57
i see ... but if you say that its already fixed then I'm fine with that!

**Comment by DzikuVx** [comment] 2018-01-24 19:32
confirmed working

**Closed by DzikuVx** 2018-01-24 19:32 UTC
