### ISSUE TITLE
MACOS BIG SUR 11.3 CRASH

### ISSUE THREAD

**Issue by al3k87** [iNavFlight/inav-configurator#1255] opened 2021-05-04 09:12 UTC
This software is not compatible with MACOS BIG SUR 11.3, it random crashes.
Please compile a new version with updated node.js

**Comment by avsaase** [comment] 2021-05-04 09:21
Duplicate of https://github.com/iNavFlight/inav-configurator/issues/1177. In the future, please provide some more information about which configurator version you are using.

**Closed by avsaase** 2021-05-04 09:21 UTC
