### ISSUE TITLE
iNav configurator 2.0.0.RC1 Tricopter mixer doesn't want to save

### ISSUE THREAD

**Issue by wilco1967** [iNavFlight/inav-configurator#491] opened 2018-06-26 19:49 UTC
In the new iNav configurator 2.0.0.RC1, the Tricopter mixer doesn't want to save.

It seems to load the proper values in the configurator, but the save & reboot button doesn't seem to have any effect....

I was able to set mixer values from CLI.

save & reboot works fine for example on a quad, but not for a tri,

**Comment by DzikuVx** [comment] 2018-06-26 19:52
Duplicate of #489 Closing

**Closed by DzikuVx** 2018-06-26 19:52 UTC

**Comment by wilco1967** [comment] 2018-06-26 19:57
ahh, sorry.... didn't see it was already reported and closed....
