### ISSUE TITLE
Motor mixer values are shown incorrectly

### ISSUE THREAD

**Issue by avsaase** [iNavFlight/inav-configurator#1164] opened 2021-01-21 10:11 UTC
When using a custom motor mixer with decimal values, such as 
```
# mmix
mmix 0  1.000 -0.887  0.723  1.000
mmix 1  1.000 -1.000 -0.723 -1.000
mmix 2  1.000  0.887  0.723 -1.000
mmix 3  1.000  1.000 -0.723  1.000
```
then the configurator shows these value incorrectly:
![image](https://user-images.githubusercontent.com/880421/105335676-a38e2f00-5bd8-11eb-9803-c1fa308d3c6f.png)

This happens with both the current master branch and release 2.6.1 for Windows 10.

**Comment by DzikuVx** [comment] 2021-01-21 10:55
It happens on all the releases and is caused by the fact that MSP layer is integer not float based

**Comment by avsaase** [comment] 2021-01-21 13:07
Wouldn't it be possible to just round it to three decimals in the configurator? Since the difference to the correct value is so small this should always lead to the same value as the CLI command.

**Comment by DzikuVx** [comment] 2022-03-14 12:52
This was fixed some time ago so closing

**Closed by DzikuVx** 2022-03-14 12:52 UTC
