### ISSUE TITLE
Feature Request: Delete the SD-CARD/Blackbox flash memory

### ISSUE THREAD

**Issue by Pairan** [iNavFlight/inav-configurator#1574] opened 2022-07-07 06:48 UTC
As I can't find such an option today in the current configurator it would be great to simply hit a button in the UI and with that wipe the contents of the SD-Card / Blackbox flash memory.

**Comment by MrD-RC** [comment] 2022-11-26 11:04
Duplicate of https://github.com/iNavFlight/inav-configurator/issues/516

**Closed by MrD-RC** 2022-11-26 11:04 UTC
