### ISSUE TITLE
Problem with launching iNav Configurator

### ISSUE THREAD

**Issue by avirotstein** [iNavFlight/inav-configurator#161] opened 2017-03-10 00:53 UTC
Launching iNav configurator (1.6.2) from the start menu (under windows 10) just opens chrome to its default start page

**Comment by DzikuVx** [comment] 2017-03-10 07:49
@avirotstein unable to confirm. Latest works fine with my both Windows 10 and Mac

**Comment by DzikuVx** [comment] 2017-06-04 11:26
Looks like this in local env. problem, so closing since unable to reproduce

**Closed by DzikuVx** 2017-06-04 11:26 UTC
