### ISSUE TITLE
  ble device on windows?

### ISSUE THREAD

**Issue by bk79** [iNavFlight/inav-configurator#2] opened 2016-05-12 16:58 UTC
I'm able to use it with ez-gui, but Not in windows with chrome configurator

**Comment by digitalentity** [comment] 2016-05-13 23:21
Please explain more. I use bluetooth to talk to my quad via Configurator no problem.

**Comment by bk79** [comment] 2016-05-14 04:48
Me too with hc-05 module but with hm-10 module(ble4.0) there is no way to
connect from the pc because Bluetooth 4.0 protocol  doesn't use a com port
so it's impossible to connect with the configurator which asks for a com
port
Il 14/mag/2016 01:21, "Konstantin Sharlaimov" <notifications@github.com> ha
scritto:

**Comment by digitalentity** [comment] 2016-05-14 04:50
Oh, I see. Need to order myself a ble module to look into the issue

**Comment by bk79** [comment] 2016-05-14 04:51
It has more range or at least they say so...
Il 14/mag/2016 06:50, "Konstantin Sharlaimov" <notifications@github.com> ha
scritto:

**Comment by bk79** [comment] 2016-05-14 04:51
Btw On ez-gui works
Il 14/mag/2016 06:50, "Konstantin Sharlaimov" <notifications@github.com> ha
scritto:

**Comment by skaman82** [comment] 2016-05-25 15:44
Have exactly the same problem. Thats why I am using hc-05 module to connect with my macbook and hm-10 module with my iPhone. It sucks to change the module depending on the device i want to connect it with but thats how it is, I guess. This is technically not a issue.

**Comment by skaman82** [comment] 2016-06-15 22:01
closing since this not a bug

**Closed by skaman82** 2016-06-15 22:01 UTC

**Comment by bk79** [comment] 2016-06-15 22:15
No it's not a bug it's a missing feature
Il 16/giu/2016 00:01, "Albert Kravcov" <notifications@github.com> ha
scritto:

**Comment by skaman82** [comment] 2016-06-15 22:20
It is a hardware issue (or missing future). It is not configurator's fault that the hardware not supporting required protocols.

**Comment by bk79** [comment] 2016-06-16 03:53
No it's the configurator that is not able to handle the ble protocol since
there is no com port on the ble created
Il 16/giu/2016 00:20, "Albert Kravcov" <notifications@github.com> ha
scritto:
