### ISSUE TITLE
GUI bug, no scrollbar for menu sidebar when in full-screen mode

### ISSUE THREAD

**Issue by csurf** [iNavFlight/inav-configurator#106] opened 2017-01-15 06:24 UTC
I found a small bug in the markup for the GUI. When the window is maximized on a small screen (laptop), the sidebar menu can be cut-off and some of the last options aren't available, such as the CLI. There's no way to scroll down when the window is maximized. However, if the window is resized, the sidebar goes into 'icon' mode and a small vertical scrollbar appears for reaching the lower options.

**Comment by skaman82** [comment] 2017-01-15 10:02
strange, I have a scroll bar if the menu items not fitting in the window size - even in normal mode

<img width="250" alt="bildschirmfoto 2017-01-15 um 10 59 29" src="https://cloud.githubusercontent.com/assets/11768024/21961721/fe55b1de-db11-11e6-8b3c-c8ec64b87e94.png">

**Comment by DzikuVx** [comment] 2017-01-15 10:28
I'm also unable to reproduce @csurf 
Which version of Configurator are you using?

**Comment by skaman82** [comment] 2017-06-08 19:33
Closing this since there has been no feedback on this for long time

**Closed by skaman82** 2017-06-08 19:33 UTC
