### ISSUE TITLE
FEATURE REQUEST: INAV 8: Sattelite view on mission control screen

### ISSUE THREAD

**Issue by samsab1** [iNavFlight/inav-configurator#2261] opened 2024-11-21 09:27 UTC
hello
In the Mission control menu, is it possible to have the choice of the map representation, either in satellite mode (with the representation of the vegetation on the ground) or in map mode?
best regards

**Comment by stronnag** [comment] 2024-11-21 10:35
Duplicate of #2130

**Closed by stronnag** 2024-11-21 10:35 UTC
