### ISSUE TITLE
Speedybeef7v2 support

### ISSUE THREAD

**Issue by AntDiskmk** [iNavFlight/inav-configurator#1313] opened 2021-07-06 20:11 UTC
Do you guys plan to add support/firmware for the speedybeef7v2 flight controller?  I tried to use the version one firmware, but it didn't work and created a lot of problems on the device.  Thank you.

**Comment by DzikuVx** [comment] 2021-07-06 20:47
Duplicate of https://github.com/iNavFlight/inav/issues/7144

**Closed by DzikuVx** 2021-07-06 20:47 UTC
